In [1]:
import numpy as np

In [18]:
arr1D=np.array([1,2,3,4,5,6])

参数的意义：第一个参数是待填充的数组，第二个参数是填充到边缘的数目，第三个参数是填充方式

constant:常数填充方式，默认为0，constant_values=(a, b)表示前面边界填充a,后面边界填充b

In [19]:
print('constant:'+str(np.pad(arr1D,(2,3),'constant')))
print('constant:'+str(np.pad(arr1D,(2,3),'constant',constant_values=(4, 7))))

constant:[0 0 1 2 3 4 5 6 0 0 0]
constant:[4 4 1 2 3 4 5 6 7 7 7]


edge:边缘值填充

In [7]:
print('edge:'+str(np.pad(arr1D,(2,3),'edge')))

edge:[1 1 1 2 3 4 5 6 6 6 6]


maximun:最大值填充,minimum:最小值，mean:平均值，median:中位数

In [24]:
print('maximum:'+str(np.pad(arr1D,(2,3),'maximum')))
print('minimun:'+str(np.pad(arr1D,(2,3),'minimum')))
print('mean:'+str(np.pad(arr1D,(2,3),'mean')))
print('median:'+str(np.pad(arr1D,(2,3),'median')))

maximum:[6 6 1 2 3 4 5 6 6 6 6]
minimun:[1 1 1 2 3 4 5 6 1 1 1]
mean:[4 4 1 2 3 4 5 6 4 4 4]
median:[4 4 1 2 3 4 5 6 4 4 4]


reflect:边缘对称填充,填充数据从边缘的下一个开始；symmetric:对称填充，从边缘值开始

In [4]:
arr2=np.array([3,5,7,8])

In [33]:
print('reflect:'+str(np.pad(arr2,(2,4),'reflect')))
print('symmetric:'+str(np.pad(arr2,(2,3),'symmetric')))

reflect:[7 5 3 5 7 8 7 5 3 5]
symmetric:[5 3 3 5 7 8 8 7 5]


linear_ramp:边缘递减的方式填充数据

In [11]:
print('linear_ramp:'+str(np.pad(arr2,(2,3),'linear_ramp')))
print('linear_ramp:'+str(np.pad(arr2,(2,3),'linear_ramp',end_values=(1,3))))

linear_ramp:[0 2 3 5 7 8 5 3 0]
linear_ramp:[1 2 3 5 7 8 6 5 3]


二维数组填充

In [2]:
arr2D=np.arange(1,5).reshape(2,2)

In [3]:
arr2D

array([[1, 2],
       [3, 4]])

In [15]:
print('2D array:'+str(np.pad(arr2D,((1,1),(1,2)),'constant')))

2D array:[[0 0 0 0 0]
 [0 1 2 0 0]
 [0 3 4 0 0]
 [0 0 0 0 0]]


3维数组填充

In [16]:
arr3D=np.array([[[1, 1, 2, 2, 3, 4], [1, 1, 2, 2, 3, 4], [1, 1, 2, 2, 3, 4]], 
                  [[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]], 
                  [[1, 1, 2, 2, 3, 4], [1, 1, 2, 2, 3, 4], [1, 1, 2, 2, 3, 4]]])

In [21]:
print('arr3D:'+str(np.pad(arr3D,((0,0),(2,2),(2,2)),'constant')))

arr3D:[[[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 1 1 2 2 3 4 0 0]
  [0 0 1 1 2 2 3 4 0 0]
  [0 0 1 1 2 2 3 4 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 1 2 3 4 5 0 0]
  [0 0 0 1 2 3 4 5 0 0]
  [0 0 0 1 2 3 4 5 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 1 1 2 2 3 4 0 0]
  [0 0 1 1 2 2 3 4 0 0]
  [0 0 1 1 2 2 3 4 0 0]
  [0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0]]]
